### ISSUE TITLE
BUG: occasional 'Cannot get /' Error on app start

### ISSUE THREAD

**Issue by marcelkilian** [mazehall/eintopf#17]
Affects starts with 'npm start' and releases

**Comment by marcelkilian** [comment]
see https://github.com/mazehall/eintopf/commit/8b045206d708720beebc626ea1592d269a382036

**Comment by marcelkilian** [comment]
Refactoring done. see https://github.com/mazehall/eintopf/commit/cc771b1b4d5a4955ff06894625d52d54353205f0

**Comment by jensklose** [comment]
restart race ;)

**Comment by marcelkilian** [comment]
The issue was an error in the setup model which stopped the gui init. The module loader emitted the gui module as ready before that.

see https://github.com/mazehall/eintopf/commit/27e4f889cfa359e08a04d0b7855619514e4a581f
