### ISSUE TITLE
Uninstalling leaves vagrant in inoperable state

### ISSUE THREAD

**Issue by dinamic** [mazehall/eintopf#67]
The following error is to be observed when trying to issue `vagrant up`:

```
NFS is reporting that your exports file is invalid. Vagrant does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:6: path contains non-directory or non-existent components: /Users/nikola/eintopf
exports:6: no usable directories in export entry
exports:6: using fallback (marked offline): /
```

**Comment by marcelkilian** [comment]
Please provide your vagrant version with the following command in the terminal:

```
vagrant -v
```

Did you change the vagrant file (default localtion is ~/.eintopf/default/Vagrantfile)?

Can you also provide  a more detailed log for vagrant up (https://www.vagrantup.com/docs/other/debugging.html)?

As a quick fix try to restart vagrant. Use the following commands:

```
cd ~/.eintopf/default
vagrant reload
```

**Comment by dinamic** [comment]
Seems like a few entries were still present in `/etc/exports`. Just be sure you have them removed when uninstalling the software.

**Comment by jensklose** [comment]
Seems like you want `vagrant up` in another not Eintopf driven vagrant project with NFS.

Eintopf is designed more as a concept with the usage of vagrant under the hood. We don`t provide an explicit uninstall. The main concept included the usage of one entry point/path to all your project sources.
How could we know that this path is unused in your NFS exports after uninstall?

I think your case is more a common vagrant issue. But I think also, that this is a "add to documentation" hint.

**Comment by dinamic** [comment]
Eintopf was uninstalled a few days back and yet it has not reverted back the `/etc/exports` file. This is why I have posted the issue. It should be considered a bug IMO.

I would guess you have no way of knowing the paths my projects are using. What I would suggest is to have some kind of troubleshooting section and for this case to be covered. Someone might stumble upon without knowing how to get the situation under control.

**Comment by jensklose** [comment]
A troubleshooting section is a great idea and your post is a step in this direction. Github and Stackoverflow are the first places for that IMO.
Currently we are under heavy development to make Eintopf a better experience and daily tool. Your feedback are welcome.
