### ISSUE TITLE
Hardcoded Icon Line

### ISSUE THREAD

**Issue by Foggalong** [mazehall/eintopf#82]
The icon path in the created [.desktop launcher file](https://github.com/mazehall/eintopf/blob/master/resources/linux/app.desktop#L8) is hardcoded to `Icon=/opt/{{name}}/icon.png`. This prevents icon theming without editing the launcher file.

I'd like to ask you to change the icon location as well as the icon path line in the launcher according to the freedesktop.org standards. Please find more info [here](http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) and [here](https://github.com/Foggalong/hardcode-fixer/wiki/What,-Why-&-How).

According to the above resources standard icon locations are:
- `/usr/share/icons/hicolor/[size]/apps/[icon name]`
- `~/.local/share/icons/hicolor/[size]/apps/[icon name]`
- `/usr/share/pixmaps/[icon name]`

When the icon is located in one of the above the corresponding standard icon line in the .desktop launcher only has to be `Icon=[icon name]`, without the full path and without file extension. In this programs case, for an icon `eintopf.svg` or `eintopf.png` stored in a standard location it would read: `Icon=eintopf`

Cf. [this example .desktop launcher](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#example).

Could you please install the icon to one of those locations and adjust the icon path in the .desktop file accordingly?

**Comment by jensklose** [comment]
pre archive closing
